Name:           ros-kinetic-thormang3-walking-module
Version:        0.2.0
Release:        0%{?dist}
Summary:        ROS thormang3_walking_module package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://wiki.ros.org/thormang3_walking_module
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       eigen3-devel
Requires:       ros-kinetic-cmake-modules
Requires:       ros-kinetic-eigen-conversions
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-robotis-controller-msgs
Requires:       ros-kinetic-robotis-framework-common
Requires:       ros-kinetic-robotis-math
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-roslib
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-thormang3-balance-control
Requires:       ros-kinetic-thormang3-kinematics-dynamics
Requires:       ros-kinetic-thormang3-walking-module-msgs
Requires:       yaml-cpp-devel
BuildRequires:  boost-devel
BuildRequires:  eigen3-devel
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cmake-modules
BuildRequires:  ros-kinetic-eigen-conversions
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-robotis-controller-msgs
BuildRequires:  ros-kinetic-robotis-framework-common
BuildRequires:  ros-kinetic-robotis-math
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-roslib
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-thormang3-balance-control
BuildRequires:  ros-kinetic-thormang3-kinematics-dynamics
BuildRequires:  ros-kinetic-thormang3-walking-module-msgs
BuildRequires:  yaml-cpp-devel

%description
This package is a motion module for thormang3 walking. This package provides a
online walking pattern generator for the thormang3.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Tue Mar 27 2018 Pyo <pyo@robotis.com> - 0.2.0-0
- Autogenerated by Bloom

* Wed May 24 2017 Pyo <pyo@robotis.com> - 0.1.3-0
- Autogenerated by Bloom

* Mon Apr 24 2017 Pyo <pyo@robotis.com> - 0.1.2-0
- Autogenerated by Bloom

* Fri Aug 19 2016 Pyo <pyo@robotis.com> - 0.1.1-0
- Autogenerated by Bloom

* Thu Aug 18 2016 Pyo <pyo@robotis.com> - 0.1.0-0
- Autogenerated by Bloom

